---
# tasks file for python
- name: "Upgrade Packages"
  ansible.builtin.yum:
    name: '*'
    state: latest
- name: "Install Dependencies"
  ansible.builtin.yum:
    name: '{{ item }}'
    state: present
  loop:
  - "epel-release"
  - "python3"
  - "python-devel"
  - "git"
