---
- name: Update Raspberry Pi and Pi-hole
  hosts: pihole
  become: true
  gather_facts: true

  vars:
    apt_cache_valid_time: 3600
    run_dist_upgrade: false

  roles:
    - system_update
    - pihole_update
