---
# tasks file for firewalld
  - name: "Upgrade Yum Packages"
    ansible.builtin.yum:
      name: '*'
      state: latest
  - name: "Install Firewalld"
    ansible.builtin.yum:
      name: firewalld
      state: present
    become: true
  - name: "Start and Enable Firewalld Service"
    ansible.builtin.service:
      name: firewalld
      state: started
      enabled: yes
