---
# tasks file for aws_ec2_uninstall

- name: Get Info about EC2 Instances
  amazon.aws.ec2_instance_info:
    profile: Nathan-Dev
    region: "{{ aws_region }}"
    filters:
      "tag:app": simple-webapp
  register: ec2info

- name: debug EC2 Info
  debug:
    var: ec2info

- name: Get Security Group Info
  amazon.aws.ec2_security_group_info:
    profile: Nathan-Dev
    region: "{{ aws_region }}"
    filters:
      "tag:app": simple-webapp
  register: ec2_sg_info

- name: debug EC2 SG Info
  debug:
    var: ec2_sg_info

- name: Get VPC Route Table Info
  amazon.aws.ec2_vpc_route_table_info:
    profile: Nathan-Dev
    region: "{{ aws_region }}"
    filters:
      "tag:app": simple-webapp
  register: rt_ansibleVPC_PublicSubnet_info

- name: display public route table
  debug:
    var: rt_ansibleVPC_PublicSubnet_info

- name: Get info of public subnet
  amazon.aws.ec2_vpc_subnet_info:
    profile: Nathan-Dev
    region: "{{ aws_region }}"
    filters:
      "tag:app": simple-webapp
  register: public_subnet_info

- name: debug VPC Subnet Info
  debug:
    var: public_subnet_info

- name: Get Gateway Info
  amazon.aws.ec2_vpc_igw_info:
    profile: Nathan-Dev
    region: "{{ aws_region }}"
    filters:
      "tag:app": simple-webapp
  register: ansibleVPC_igw_info

- name: debug VPC IGW Info
  debug:
    var: ansibleVPC_igw_info

- name: Get Info of the VPCs
  amazon.aws.ec2_vpc_net_info:
    profile: "{{ aws_profile }}"
    filters:
      "tag:Name": "{{ resource_name_prefix }}-vpc"
  register: ansibleVPC_info

- name: debug VPC
  debug:
    var: ansibleVPC_info

- name: Terminate Instances
  amazon.aws.ec2_instance:
    profile: Nathan-Dev
    key_name: "simple-webapp-key"
    vpc_subnet_id: "{{ public_subnet_info.subnets[0].id }}"
    instance_type: "{{ instance_type }}"
    security_group:   "{{ ec2_sg_info.security_groups[0].group_id }}"
    image_id: "{{ ec2info.instances[0].image_id }}"
    region: "{{ aws_region }}"
    state: absent
    network:
      assign_public_ip: true
    tags:
      Name: "{{ item }}"
      app: simple-webapp
  with_items: "{{ instance_list }}"
  ignore_errors: yes

- name: Delete SSH Key
  ec2_key:
    profile: Nathan-Dev
    region: "{{ aws_region }}"
    name: "simple-webapp-key"
    state: absent