services:
  node1:
    build: .
    container_name: ansible-node1
    ports:
      - "2222:22"
    environment:
      - USER=ansible

  node2:
    build: .
    container_name: ansible-node2
    ports:
      - "2223:22"
    environment:
      - USER=ansible