---
# tasks file for aws_network_uninstall
  - name: Remove Security Group
    ec2_group:
      profile: "{{ aws_profile }}"
      region: "{{ aws_region }}"
      name: "{{ resource_name_prefix }}-sg"
      description: "Test Security Group"
      state: absent
      vpc_id: "{{ ansibleVPC_info.vpcs[0].id }}"
      tags:
        name: "{{ resource_name_prefix }}-sg"
      rules:
      - proto: "tcp"
        ports: "22"
        cidr_ip: 0.0.0.0/0

  - name: Remove Public Subnet Route Table
    ec2_vpc_route_table:
      profile: "{{ aws_profile }}"
      region: "{{ aws_region }}"
      #name: "{{ resource_name_prefix }}-rt"
      state: absent
      vpc_id: "{{ ansibleVPC_info.vpcs[0].id }}"
      tags:
        name: "{{ resource_name_prefix }}-rt"
      subnets:
      - "{{ public_subnet_info.subnets[0].id }}"
      routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ ansibleVPC_igw_info.internet_gateways[0].internet_gateway_id }}"
    register: rt_ansibleVPC_info_PublicSubnet_info

  - name: display public route table
    debug:
      var: rt_ansibleVPC_PublicSubnet_info

  - name: Remove the Public Subnet
    ec2_vpc_subnet:
      profile: "{{ aws_profile }}"
      region: "{{ aws_region }}"
      state: absent
      cidr: 10.10.0.0/16
      vpc_id: "{{ ansibleVPC_info.vpcs[0].id }}"
      map_public: yes
      tags:
        name: "{{ resource_name_prefix }}-public_subnet"
    register: public_subnet

  - name: Remove the Internet Gateway
    ec2_vpc_igw:
      region: "{{ aws_region }}"
      profile: "{{ aws_profile }}"
      state: absent
      vpc_id: "{{ ansibleVPC_info.vpcs[0].id }}"
      tags:
        name: "{{ resource_name_prefix }}-igw"
    register: ansibleVPC_info_igw

  - name: Remove the VPC
    ec2_vpc_net:
      region: "{{ aws_region }}"
      profile: "{{ aws_profile }}"
      name:  "{{ resource_name_prefix }}-vpc"
      cidr_block: 10.10.0.0/16
      state: absent
      tags:
        module: ec2_vpc_net
        name: "{{ resource_name_prefix }}-vpc"
      tenancy: default
    register: ansibleVPC_info