---
# tasks file for python_uninstall
   - name: "Uninstall Dependencies"
     ansible.builtin.yum:
       name: '{{ item }}'
       state: absent
     loop:
     - "epel-release"
     - "python3"
     - "python-devel"
     - "git"
