---
# tasks file for flask_web
- name: "Install Python Flask Dependencies"
  ansible.builtin.pip:
    name:
    - "Flask"
    - "Flask-MySQL"
    executable: pip3
- name: "Check if Application Repo Exists"
  stat:
    path: /opt/app.py
  register: app_exists
- name: "Report Application Repo Exists"
  debug:
    msg: "Application is already on system"
  when: app_exists.stat.exists
- name: "Report if Application Does not Repo Exists"
  debug:
    msg: "Application is not on system"
  when: not app_exists.stat.exists
- name: "Copy Application Repo"
  ansible.builtin.copy:
    src: app.py
    dest: /opt/app.py
  when: not app_exists.stat.exists
- name: "Run WebSever"
  environment:
    MYSQL_DATABASE_HOST: "{{ db_server_ip }}"
  shell: FLASK_APP=/opt/app.py nohup python3 -m flask run --host=0.0.0.0 &
- name: "Test httpd webhost"
  uri:
    url: http://localhost:5000
    return_content: yes
