# SPDX-License-Identifier: MIT-0
---
# tasks file for apt-update

- name: Update apt package cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: "{{ apt_cache_valid_time }}"

- name: Upgrade installed apt packages
  ansible.builtin.apt:
    upgrade: safe

- name: Optionally perform dist-upgrade
  ansible.builtin.apt:
    upgrade: dist
  when: run_dist_upgrade | bool

- name: Remove unnecessary packages
  ansible.builtin.apt:
    autoremove: true
    autoclean: true
