# Ansible Playbook - Update System Packages
- name: Update system packages in WSL
  hosts: localhost
  become: true
  gather_facts: no
  tasks:
  - name: "Upgrade WSL Packages"
    apt:
      name: '*'
      state: latest
