- name: "Setup Target 2 for Web Application Database Hosting"
  hosts: ansible-target2
  become: true # set for privilege escalation at playbook scope
  roles:
  - firewalld
  - mariadb

- name: "Setup Target1 for Web Application Hosting"
  hosts: ansible-target1
  become: true
  roles:
  - firewalld
  - ecommerce_app
