- name: "Undo Setup Target 2 for Web Application Database Hosting"
  hosts: ansible-target2
  become: true # set for privilege escalation at playbook scope
  vars_files:
  - ./vars/db_creds.yaml 
  - ./vars/server_ips.yaml
  tasks:
  - name: "Delete user ecomuser in MariaDB accessing from WebSever (Target1)"
    mysql_user:
        name: '{{ db_user }}'
        password: '{{ db_password }}'
        host: '{{ web_server_ip }}'
        state: absent
  - name: "Delete ecomdb MariaDB Database"
    mysql_db:
      name: '{{ db_name }}'
      state: absent
  - name: 'uninstalling python-3 mysql libraries'
    yum: 
      name: MySQL-python
      state: absent
  - name: "Uninstall MariaDB"
    yum:
      name: mariadb-server
      state: absent
    become: true 
  - name: "Uninstall Firewalld"
    yum:
      name: firewalld
      state: present
    become: true

- name: "Undo  Target1 for Web Application Hosting"
  hosts: ansible-target1
  become: true
  tasks:
  - name: "Check if GitHub Repo is on system"
    stat:
      path: /var/www/html/README.md
    register: git_exists
  - name: "Delete  Application Repo"
    command: rm -r /var/www/html/
    when: git_exists.stat.exists == True
  - name: "Uninstall git to clone source code down"
    yum:
      name: git
      state: absent
  - name: "Uninstall Required Packages for Apache Web Server"
    yum: 
      name: '{{item}}'
      state: absent
    become: true
    loop:
    - httpd
    - php
    - php-mysql
  - name: "Uninstall Firewalld"
    yum:
      name: firewalld
      state: absent
    become: true
