# Ansible Playbook - Deploy AWS Infrastructure
- name: Deploy AWS Infrastructure for Distributed Application
  hosts: localhost
  gather_facts: no
  roles:
  - aws_network
  - aws_ec2

- name: Setup Database
  hosts: db_servers
  connection: ssh
  roles:
  - python
  - mysql_db 


- name: Setup Web Server
  hosts: web_servers
  connection: ssh
  roles:
  - python
  - flask_web