---
# tasks file for aws_ec2
- name: Find AMIs published by Red Hat (309956199498) that are Non-beta and x86 architecture
  ec2_ami_info:
    profile: Nathan-Dev
    region: "{{ aws_region }}"
    owners: 309956199498
    filters:
      architecture: x86_64
      name: RHEL-8*HVM-*
  register: amis

- name: Show the AMIs
  debug:
    var: amis

- name: Get the latest AMI from the list provided
  set_fact:
    latest_ami: "{{ amis.images | sort(attribute='creation_date') | last }}"

- name: Create SSH Key
  ec2_key:
    profile: Nathan-Dev
    region: "{{ aws_region }}"
    name: "{{ ssh_keyname }}-simple-webapp"
  register: ec2_key_result

- name: Save private key
  copy: 
    content: "{{ ec2_key_result.key.private_key }}"
    dest: "./demo_key.pem"
    mode: 0600
  when: ec2_key_result.changed

- name: Launch Web and DB Server Instances
  amazon.aws.ec2_instance:
    profile: Nathan-Dev
    name: "{{ item }}"
    key_name: "{{ ssh_keyname }}-simple-webapp"
    vpc_subnet_id: "{{ public_subnet.subnet.id }}"
    instance_type: "{{ instance_type }}"
    security_group: "{{ my_vpc_sg.group_id }}"
    image_id: "{{ latest_ami.image_id }}"
    region: "{{ aws_region }}"
    state: running
    wait: true
    network:
      assign_public_ip: true
    tags:
      Name: "{{ item }}"
      app: simple-webapp
  with_items: "{{ instance_list }}"
  register: ec2_creation_info
    
- name: print the results
  debug:
    var: ec2_creation_info

#- name: wait for ssh connection to be available
#  wait_for: host={{ item.public_ip_address }} port=22 delay=10 timeout=60
#  with_items: "{{ ec2_creation_info.results[0].instances[0] }}"

#- name: Add db-server to in-memory inventory
#  add_host: hostname={{ item.public_ip_address }} private_ip={{ item.private_ip_address }} groupname=db_servers
#  with_items: "{{ ec2info.instances }}"

#- name: Add db-server to in-memory inventory
#  ansible.builtin.add_host:
#    hostname:
#    groups:

