---
# tasks file for mysql_db_uninstall
   - name: "Delete Application Database"
     community.mysql.mysql_db:
       name: "{{ db_name }}"
       state: absent
   - name: "Uninstall pip"
     yum:
       name: "python-pip"
       state: absent
   - name: "Uninstall MySQL database"
     yum:
       name: "{{ item }}"
       state: absent
     loop:
        - "mysql-server"
        - "mysql-devel"
   - name: "Uninstall MySQL Community Repository"
     yum:
       name: "http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm"
       state: absent

